repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0  # Utilisez la dernière version
    hooks:
      # Linter avec correction automatique
      - id: ruff
        args: ["--fix"]
      # Formateur
      - id: ruff-format